name: Publish

permissions:
  contents: write
  packages: write

on:
  workflow_call:
    inputs:
      git_ref:
        type: string
        required: true
        # channel is the dir/namespace packages are organized into.
        # Options are release/nightly/custom.
      channel:
        type: string
        required: true

env:
  VERBOSE: true
  CI: true
  DISABLE_MOLD: true
  DEBIAN_FRONTEND: noninteractive
  CONTAINER_TOOL: docker
  CARGO_PROFILE_RELEASE_LTO: fat
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
  CHANNEL: ${{ inputs.channel }}

jobs:
  generate-publish-metadata:
    name: Generate Publish-related Metadata
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      vector_version: ${{ steps.generate-publish-metadata.outputs.vector_version }}
      vector_build_desc: ${{ steps.generate-publish-metadata.outputs.vector_build_desc }}
      vector_release_channel: ${{ steps.generate-publish-metadata.outputs.vector_release_channel }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Generate publish metadata
        id: generate-publish-metadata
        run: make ci-generate-publish-metadata

  build-x86_64-unknown-linux-musl-packages:
    name: Build Vector for x86_64-unknown-linux-musl (.tar.gz)
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    needs: generate-publish-metadata
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
      VECTOR_BUILD_DESC: ${{ needs.generate-publish-metadata.outputs.vector_build_desc }}
      CHANNEL: ${{ needs.generate-publish-metadata.outputs.vector_release_channel }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Bootstrap runner environment (Ubuntu-specific)
        run: sudo -E bash scripts/environment/bootstrap-ubuntu-24.04.sh
      - name: Bootstrap runner environment (generic)
        run: bash scripts/environment/prepare.sh --modules=rustup,cross
      - name: Build Vector
        run: make package-x86_64-unknown-linux-musl-all
      - name: Stage package artifacts for publish
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-musl
          path: target/artifacts/vector*

  build-x86_64-unknown-linux-gnu-packages:
    name: Build Vector for x86_64-unknown-linux-gnu (.tar.gz, DEB, RPM)
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    needs: generate-publish-metadata
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
      VECTOR_BUILD_DESC: ${{ needs.generate-publish-metadata.outputs.vector_build_desc }}
      CHANNEL: ${{ needs.generate-publish-metadata.outputs.vector_release_channel }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Bootstrap runner environment (Ubuntu-specific)
        run: sudo -E bash scripts/environment/bootstrap-ubuntu-24.04.sh
      - name: Bootstrap runner environment (generic)
        run: bash scripts/environment/prepare.sh --modules=rustup,cross
      - name: Build Vector
        run: make package-x86_64-unknown-linux-gnu-all
      - name: Stage package artifacts for publish
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-gnu
          path: target/artifacts/vector*

  build-aarch64-unknown-linux-musl-packages:
    name: Build Vector for aarch64-unknown-linux-musl (.tar.gz)
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    needs: generate-publish-metadata
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
      VECTOR_BUILD_DESC: ${{ needs.generate-publish-metadata.outputs.vector_build_desc }}
      CHANNEL: ${{ needs.generate-publish-metadata.outputs.vector_release_channel }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Bootstrap runner environment (Ubuntu-specific)
        run: sudo -E bash scripts/environment/bootstrap-ubuntu-24.04.sh
      - name: Bootstrap runner environment (generic)
        run: bash scripts/environment/prepare.sh --modules=rustup,cross
      - name: Build Vector
        env:
          DOCKER_PRIVILEGED: "true"
        run: make package-aarch64-unknown-linux-musl-all
      - name: Stage package artifacts for publish
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-musl
          path: target/artifacts/vector*

  build-aarch64-unknown-linux-gnu-packages:
    name: Build Vector for aarch64-unknown-linux-gnu (.tar.gz)
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    needs: generate-publish-metadata
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
      VECTOR_BUILD_DESC: ${{ needs.generate-publish-metadata.outputs.vector_build_desc }}
      CHANNEL: ${{ needs.generate-publish-metadata.outputs.vector_release_channel }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Bootstrap runner environment (Ubuntu-specific)
        run: sudo -E bash scripts/environment/bootstrap-ubuntu-24.04.sh
      - name: Bootstrap runner environment (generic)
        run: bash scripts/environment/prepare.sh --modules=rustup,cross
      - name: Build Vector
        env:
          DOCKER_PRIVILEGED: "true"
        run: make package-aarch64-unknown-linux-gnu-all
      - name: Stage package artifacts for publish
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-gnu
          path: target/artifacts/vector*

  build-armv7-unknown-linux-gnueabihf-packages:
    name: Build Vector for armv7-unknown-linux-gnueabihf (.tar.gz)
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    needs: generate-publish-metadata
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
      VECTOR_BUILD_DESC: ${{ needs.generate-publish-metadata.outputs.vector_build_desc }}
      CHANNEL: ${{ needs.generate-publish-metadata.outputs.vector_release_channel }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Bootstrap runner environment (Ubuntu-specific)
        run: sudo -E bash scripts/environment/bootstrap-ubuntu-24.04.sh
      - name: Bootstrap runner environment (generic)
        run: bash scripts/environment/prepare.sh --modules=rustup,cross
      - name: Build Vector
        env:
          DOCKER_PRIVILEGED: "true"
        run: make package-armv7-unknown-linux-gnueabihf-all
      - name: Stage package artifacts for publish
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-gnueabihf
          path: target/artifacts/vector*

  build-armv7-unknown-linux-musleabihf-packages:
    name: Build Vector for armv7-unknown-linux-musleabihf (.tar.gz)
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    needs: generate-publish-metadata
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
      VECTOR_BUILD_DESC: ${{ needs.generate-publish-metadata.outputs.vector_build_desc }}
      CHANNEL: ${{ needs.generate-publish-metadata.outputs.vector_release_channel }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Bootstrap runner environment (Ubuntu-specific)
        run: sudo -E bash scripts/environment/bootstrap-ubuntu-24.04.sh
      - name: Bootstrap runner environment (generic)
        run: bash scripts/environment/prepare.sh --modules=rustup,cross
      - name: Build Vector
        env:
          DOCKER_PRIVILEGED: "true"
        run: make package-armv7-unknown-linux-musleabihf
      - name: Stage package artifacts for publish
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-musleabihf
          path: target/artifacts/vector*

  build-arm-unknown-linux-gnueabi-packages:
    name: Build Vector for arm-unknown-linux-gnueabi (.tar.gz)
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    needs: generate-publish-metadata
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
      VECTOR_BUILD_DESC: ${{ needs.generate-publish-metadata.outputs.vector_build_desc }}
      CHANNEL: ${{ needs.generate-publish-metadata.outputs.vector_release_channel }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Bootstrap runner environment (Ubuntu-specific)
        run: sudo -E bash scripts/environment/bootstrap-ubuntu-24.04.sh
      - name: Bootstrap runner environment (generic)
        run: bash scripts/environment/prepare.sh --modules=rustup,cross
      - name: Build Vector
        env:
          DOCKER_PRIVILEGED: "true"
        run: make package-arm-unknown-linux-gnueabi-all
      - name: Stage package artifacts for publish
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-arm-unknown-linux-gnueabi
          path: target/artifacts/vector*

  build-arm-unknown-linux-musleabi-packages:
    name: Build Vector for arm-unknown-linux-musleabi (.tar.gz)
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    needs: generate-publish-metadata
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
      VECTOR_BUILD_DESC: ${{ needs.generate-publish-metadata.outputs.vector_build_desc }}
      CHANNEL: ${{ needs.generate-publish-metadata.outputs.vector_release_channel }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Bootstrap runner environment (Ubuntu-specific)
        run: sudo -E bash scripts/environment/bootstrap-ubuntu-24.04.sh
      - name: Bootstrap runner environment (generic)
        run: bash scripts/environment/prepare.sh --modules=rustup,cross
      - name: Build Vector
        env:
          DOCKER_PRIVILEGED: "true"
        run: make package-arm-unknown-linux-musleabi
      - name: Stage package artifacts for publish
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-arm-unknown-linux-musleabi
          path: target/artifacts/vector*

  deb-verify:
    name: Verify DEB Packages
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    needs:
      - generate-publish-metadata
      - build-x86_64-unknown-linux-gnu-packages
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
      DD_PKG_VERSION: "latest"
    strategy:
      matrix:
        container:
          - ubuntu:20.04
          - ubuntu:22.04
          - ubuntu:24.04
          - debian:11
          - debian:12
          - debian:13
    container:
      image: ${{ matrix.container }}
    steps:
      - run: |
          apt-get update && \
          apt-get install -y \
          ca-certificates \
          curl \
          git \
          systemd \
          make
      - name: Install dd-pkg for linting
        run: |
          curl -sSL "https://dd-package-tools.s3.amazonaws.com/dd-pkg/${DD_PKG_VERSION}/dd-pkg_Linux_x86_64.tar.gz" | tar -xz -C /usr/local/bin dd-pkg
      - name: Fix Git safe directories issue when in containers (actions/checkout#760)
        run: git config --global --add safe.directory /__w/vector/vector
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Download staged package artifacts (x86_64-unknown-linux-gnu)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-gnu
          path: target/artifacts
      - name: Verify install of DEB package.
        run: |
          ./scripts/verify-install.sh target/artifacts/vector_${{ env.VECTOR_VERSION }}-1_amd64.deb

  rpm-verify:
    name: Verify RPM Packages
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    needs:
      - generate-publish-metadata
      - build-x86_64-unknown-linux-gnu-packages
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
      DD_PKG_VERSION: "latest"
    strategy:
      matrix:
        container:
          - "quay.io/centos/centos:stream9"
          - "amazonlinux:2023"
          - "fedora:39"
          - "fedora:40"
    container:
      image: ${{ matrix.container }}
    steps:
      - run: |
          yum update -y
          yum install -y \
          ca-certificates \
          git \
          systemd \
          tar \
          make
          # conflicts with curl-minimal on some distros and --allowerased is not
          # supported on some distros
          if ! command -v curl &> /dev/null ; then
            yum install -y curl
          fi
      - name: Install dd-pkg for linting
        run: |
          curl -sSL "https://dd-package-tools.s3.amazonaws.com/dd-pkg/${DD_PKG_VERSION}/dd-pkg_Linux_x86_64.tar.gz" | tar -xz -C /usr/local/bin dd-pkg
      - name: Fix Git safe directories issue when in containers (actions/checkout#760)
        run: git config --global --add safe.directory /__w/vector/vector
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Download staged package artifacts (x86_64-unknown-linux-gnu)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-gnu
          path: target/artifacts
      - name: Verify install of RPM package.
        run: |
          ./scripts/verify-install.sh target/artifacts/vector-${{ env.VECTOR_VERSION }}-1.x86_64.rpm

  generate-sha256sum:
    name: Generate SHA256 checksums
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    needs:
      - generate-publish-metadata
      - build-x86_64-unknown-linux-gnu-packages
      - build-x86_64-unknown-linux-musl-packages
      - build-aarch64-unknown-linux-musl-packages
      - build-aarch64-unknown-linux-gnu-packages
      - build-armv7-unknown-linux-gnueabihf-packages
      - build-armv7-unknown-linux-musleabihf-packages
      - build-arm-unknown-linux-gnueabi-packages
      - build-arm-unknown-linux-musleabi-packages
    env:
      VECTOR_VERSION: ${{ needs.generate-publish-metadata.outputs.vector_version }}
    steps:
      - name: Checkout Vector
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ inputs.git_ref }}
      - name: Download staged package artifacts (aarch64-unknown-linux-gnu)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-gnu
          path: target/artifacts
      - name: Download staged package artifacts (aarch64-unknown-linux-musl)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-aarch64-unknown-linux-musl
          path: target/artifacts
      - name: Download staged package artifacts (x86_64-unknown-linux-gnu)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-gnu
          path: target/artifacts
      - name: Download staged package artifacts (x86_64-unknown-linux-musl)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-x86_64-unknown-linux-musl
          path: target/artifacts
      - name: Download staged package artifacts (armv7-unknown-linux-gnueabihf)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-gnueabihf
          path: target/artifacts
      - name: Download staged package artifacts (armv7-unknown-linux-musleabihf)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-armv7-unknown-linux-musleabihf
          path: target/artifacts
      - name: Download staged package artifacts (arm-unknown-linux-gnueabi)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-arm-unknown-linux-gnueabi
          path: target/artifacts
      - name: Download staged package artifacts (arm-unknown-linux-musleabi)
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-arm-unknown-linux-musleabi
          path: target/artifacts
      - name: Generate SHA256 checksums for artifacts
        run: make sha256sum
      - name: Stage checksum for publish
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: vector-${{ env.VECTOR_VERSION }}-SHA256SUMS
          path: target/artifacts/vector-${{ env.VECTOR_VERSION }}-SHA256SUMS
